import { createDefaultFlowDefinition, deserializeFlowDefinition, type FlowEntry, type FlowDefinition } from "@/lib/chatbots-core"

interface FlowSeedSpec extends Omit<FlowEntry, "definition"> {
  definition?: FlowDefinition
}

function buildSeedFlow(spec: FlowSeedSpec): FlowEntry {
  return {
    ...spec,
    description: spec.description.trim(),
    trigger: spec.trigger.trim(),
    testPhone: spec.testPhone?.trim() || undefined,
    keywords: spec.keywords.map((keyword) => keyword.trim()).filter(Boolean),
    definition: deserializeFlowDefinition(spec.definition ?? createDefaultFlowDefinition(spec.name), spec.name),
    n8nSyncStatus: spec.n8nSyncStatus,
    lastPublishedAt: spec.lastPublishedAt ?? undefined,
    lastTestScore: typeof spec.lastTestScore === "number" && Number.isFinite(spec.lastTestScore) ? spec.lastTestScore : undefined,
    lastTestStatus: spec.lastTestStatus?.trim() || undefined,
  }
}

const seedSpecs: FlowSeedSpec[] = [
  {
    id: 1,
    name: "NYM oficial",
    description: "Fluxo principal da operação.",
    trigger: "Primeira mensagem",
    active: false,
    conversations: 1240,
    testPhone: "(85) 99999-1001",
    keywords: ["nym", "oficial"],
    isServiceFlow: true,
    n8nSyncStatus: "success",
    lastTestScore: 92,
    lastTestStatus: "Excelente",
  },
  {
    id: 2,
    name: "Teste - Tiago Rezende",
    description: "Fluxo de validação comercial.",
    trigger: "Palavra-chave: teste",
    active: true,
    conversations: 532,
    testPhone: "(85) 99999-1002",
    keywords: ["teste", "tiago"],
    isServiceFlow: false,
    n8nSyncStatus: "success",
    lastTestScore: 88,
    lastTestStatus: "Excelente",
  },
  {
    id: 3,
    name: "Vini",
    description: "Rotina de pré-atendimento.",
    trigger: "Palavra-chave: vini",
    active: false,
    conversations: 89,
    testPhone: "(85) 99999-1003",
    keywords: ["vini"],
    isServiceFlow: false,
    n8nSyncStatus: "idle",
    lastTestScore: 65,
    lastTestStatus: "Precisa melhorar",
  },
  {
    id: 4,
    name: "teste Rafael",
    description: "Fluxo de teste para a fila comercial.",
    trigger: "Palavra-chave: rafael",
    active: false,
    conversations: 244,
    testPhone: "(85) 99999-1004",
    keywords: ["rafael", "comercial"],
    isServiceFlow: true,
    n8nSyncStatus: "success",
    lastTestScore: 81,
    lastTestStatus: "Satisfatório",
  },
  {
    id: 5,
    name: "teste de Mariana Andrade",
    description: "Automação de triagem inicial.",
    trigger: "Palavra-chave: mariana",
    active: false,
    conversations: 318,
    testPhone: "(85) 99999-1005",
    keywords: ["mariana", "triagem"],
    isServiceFlow: false,
    n8nSyncStatus: "success",
    lastTestScore: 84,
    lastTestStatus: "Satisfatório",
  },
  {
    id: 6,
    name: "(Fluxo Duplicado) Chatbase (não mexer)",
    description: "Cópia preservada do fluxo de integração.",
    trigger: "Palavra-chave: chatbase",
    active: false,
    conversations: 74,
    testPhone: "(85) 99999-1006",
    keywords: ["chatbase", "duplicado"],
    isServiceFlow: true,
    n8nSyncStatus: "error",
    lastTestScore: 72,
    lastTestStatus: "Satisfatório",
  },
  {
    id: 7,
    name: "(Fluxo Duplicado) BETA - ChatBot com Agente de IA",
    description: "BETA interno para experimentos.",
    trigger: "Palavra-chave: beta",
    active: false,
    conversations: 105,
    testPhone: "(85) 99999-1007",
    keywords: ["beta", "agente de ia"],
    isServiceFlow: false,
    n8nSyncStatus: "idle",
    lastTestScore: 69,
    lastTestStatus: "Precisa melhorar",
  },
  {
    id: 8,
    name: "Novo teste de Mariana Andrade",
    description: "Nova versão de atendimento da Mariana.",
    trigger: "Palavra-chave: nova versão",
    active: true,
    conversations: 210,
    testPhone: "(85) 99999-1008",
    keywords: ["mariana", "nova versão"],
    isServiceFlow: false,
    n8nSyncStatus: "success",
    lastTestScore: 90,
    lastTestStatus: "Excelente",
  },
  {
    id: 9,
    name: "teste",
    description: "Fluxo curto de validação.",
    trigger: "Primeira mensagem",
    active: false,
    conversations: 12,
    testPhone: "(85) 99999-1009",
    keywords: ["teste"],
    isServiceFlow: false,
    n8nSyncStatus: "idle",
    lastTestScore: 63,
    lastTestStatus: "Precisa melhorar",
  },
  {
    id: 10,
    name: "teste paulo h",
    description: "Fluxo de apoio em homologação.",
    trigger: "Palavra-chave: paulo",
    active: true,
    conversations: 96,
    testPhone: "(85) 99999-1010",
    keywords: ["paulo", "homologação"],
    isServiceFlow: true,
    n8nSyncStatus: "success",
    lastTestScore: 86,
    lastTestStatus: "Excelente",
  },
]

export function createSeedChatbotFlows() {
  return seedSpecs.map((spec) => buildSeedFlow(spec))
}
